# -*- coding: utf-8 -*-
"""week 3.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcTiF-rMTDQhXZurQr-ECzKGi3Bz7fbK
"""

#Lists
Shopping=["Bread","Coffee","Sugar","Juice"]
print(Shopping)

for item in Shopping:
  print(item)

Students=["Abhi","Lakshmi","Sridevi","Haritha","Nandini"]
for i in Students:
  print("The Students are:", i)

#append
Students.append("Raju")
print(Students)

for i in Students:
  print(i)

#indexing [position holder]
print(Students[0])
print(Students[1])
print(Students[2])
print(Students[3])
print(Students[4])
print(Students[5])

for i in range(4):
  print(Students[i])

Shopping.append("Tea")
print(Shopping)

for i in Shopping:
  print(i)

Shopping.insert(2,"Biscuits")
print(Shopping)

for i in Shopping:
  print(i)

#Create a dataset

ages=[12,32,78,34,81,18,56,23,29,30,20,19,53,86,18,18,12]

#How many people of age 18 live in a city

ages.count(18)

ages.count(12)

ages.count(100)  #100 is not in the list so it returns 0

len(ages)

len(Students)

len(Shopping)

for i in range(len(Shopping)):
  print(Shopping[i])

for i in range (len(Students)):
  print(Students[i])

for i in range (len(ages)):
  print(ages[i])

#List : Operations

#1).COUNT
ages.count(56)

#To arrange in ascending  in a proper order use Sort function

ages.sort()

print(ages)

#to print in desending order.. first sort them and then reverse them..

ages.reverse()
print(ages)

Students.sort()
print(Students)

Students.reverse()
print(Students)

Shopping.sort()
print(Shopping)

Shopping.reverse()
print(Shopping)

Shopping.insert(0,"Oil")
print (Shopping)

#Slicing
#list name[Start index: end index]
Shopping[1:6]

ages[0:12]

Students[2:5]

Students[2:]

Students[:6]

ages[:18]

Shopping[4:]

